version: '3'

services:
    laravel:
        container_name: saude-laravel
        build:
            context: .
            dockerfile: ./.docker/laravel/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/laravel
        links:
            - db
        restart: always
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: saude-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ti_saude
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local

